services:
  - type: web
    name: pencarimovie-server
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /healthz.php
    disk:
      name: pencarimovie-storage
      mountPath: /app/storage
      sizeGB: 1
